version: '3'

services:
  sqlserver_testesintegracao:
    container_name: sqlserver_testesintegracao
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    volumes:
      - testesintegracao_sqlserver_data:/mcr.microsoft.com/mssql/server

volumes:
  testesintegracao_sqlserver_data:
